<div class="row-fluid ozCon">
<?php 
echo $this->partial('tabOZ.phtml','default',array(
		'controller'=>$this->clr,
		'action' => $this->act
));
?>
<div class="media">
  <a class="pull-left" href="#">
    <img class="media-object" src="http://placehold.it/64x64">
  </a>
  <div class="media-body">
    <h4 class="media-heading">Media heading</h4>
    ...
 
    <!-- Nested media object -->
    <div class="media">
      ...
    </div>
  </div>
</div>