<?php
function myTruncate($string, $limit, $break=" ", $pad="...")
{
  // return with no change if string is shorter than $limit
  if(strlen($string) <= $limit) return $string;

  // is $break present between $limit and the end of the string?
  if(false !== ($breakpoint = strpos($string, $break, $limit))) {
    if($breakpoint < strlen($string) - 1) {
      $string = substr($string, 0, $breakpoint) . $pad;
    }
  }

  return $string;
}
?>
<div class="body">
    <a href="<?php echo $this->baseUrl();?>/admin/news/add"><i class="icon-pencil"></i> Create news<a/>
	<table style="font-size:12px;" class="table">  
        <thead>  
          <tr>  
          	<th>#</th>
            <th>Title</th> 
            <th>Date</th>
            <th>Type</th>  
            <th>User</th>
            <th>Controls</th>
            <th></th> 
          </tr>  
        </thead>  
        <tbody> 
		<?php $i=1; foreach ($this->news as $value ) { ?>
          <tr> 
            <td><?php echo $i; ?></td>         	 
            <td><?php echo myTruncate($value['title'], 20); ?></td>
            <td><?php echo $value['etime']; ?></td> 
            <td>
                <?php 
                    switch ($value['type']) {
                        case '2':
                            echo "Student Article";
                            break;                            
                        case '3':
                            echo "News";
                            break;
                       case '4':
                            echo "Page";
                            break;                            
                       case '5':
                            echo "Teacher Article";
                            break;
                        default:
                            
                            break;
                    }
                ?>
            </td> 
            <td>
                <?php
                    foreach ($this->userinfo as $uname ) {
                        if($uname['uid'] == $value['uid'])
                            $username = $uname['username'];    
                    } 
                    echo $username; 
                ?>
            </td> 
            <td><a href="<?php echo $this->baseUrl();?>/admin/news/edit/nid/<?php echo $value['id'];?>" class="btn"><i class="icon-edit"></i></a>
                <a href="<?php echo $this->baseUrl();?>/admin/news/del/nid/<?php echo $value['id'];?>" class="btn" ><i class="icon-trash"></i> </a></td> 
          </tr> 
          <?php $i++;}?>   
        </tbody>  
	</table>  
	<?= $this->paginationControl($this->news, 'Sliding', 'pagination.phtml'); ?>
</div>