<?php
    if($this->pages==NULL)
        echo "<h3 style='color:red;'>Not Found </h3>";
    else{?>
<div class="body">
    <h4><?php echo $this->pages->title;?></h4>
    <div style="margin-top:5px;">
        <?php 
        if($this->identity!=null)
            if($this->identity->role == 'admin'){?>
                    <div style="float:right; margin: 0px;" class="btn-toolbar">
                        <div class="btn-group">
                             <a href="<?php echo $this->baseUrl();?>/admin/news/edit/nid/<?php echo $this->pages->id;?>" class="btn disabled "><i class="icon-wrench"></i></a>
                             <a href="<?php echo $this->baseUrl();?>/admin/news/del/nid/<?php echo $this->pages->id;?>" class="btn disabled "><i class="icon-trash"></i></a>
                        </div>
                    </div>
        <?php }?>       
    </div>
    <p style="margin-top: 5px;"><?php echo $this->pages->content;?></p>
</div>    
<?php }?>
